#pragma checksum "..\..\..\Views\AdminCodeWindow.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "502611515E80F7F14EFA5327B41EAF565F1BF785"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using FFPOS.Controls;
using MaterialDesignThemes.Wpf;
using MaterialDesignThemes.Wpf.Converters;
using MaterialDesignThemes.Wpf.Transitions;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace FFPOS.Views {
    
    
    /// <summary>
    /// AdminCodeWindow
    /// </summary>
    public partial class AdminCodeWindow : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 157 "..\..\..\Views\AdminCodeWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.PasswordBox CodeBox;
        
        #line default
        #line hidden
        
        
        #line 164 "..\..\..\Views\AdminCodeWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock ErrorText;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.10.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/TIJORAT_PRO_POS;component/views/admincodewindow.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\Views\AdminCodeWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.10.0")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal System.Delegate _CreateDelegate(System.Type delegateType, string handler) {
            return System.Delegate.CreateDelegate(delegateType, this, handler);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.10.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            
            #line 17 "..\..\..\Views\AdminCodeWindow.xaml"
            ((FFPOS.Views.AdminCodeWindow)(target)).KeyDown += new System.Windows.Input.KeyEventHandler(this.WindowKeyDown);
            
            #line default
            #line hidden
            return;
            case 2:
            
            #line 108 "..\..\..\Views\AdminCodeWindow.xaml"
            ((System.Windows.Controls.Border)(target)).PreviewMouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.HeaderMouseLeftButtonDown);
            
            #line default
            #line hidden
            return;
            case 3:
            this.CodeBox = ((System.Windows.Controls.PasswordBox)(target));
            
            #line 160 "..\..\..\Views\AdminCodeWindow.xaml"
            this.CodeBox.PasswordChanged += new System.Windows.RoutedEventHandler(this.CodeChanged);
            
            #line default
            #line hidden
            return;
            case 4:
            this.ErrorText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 5:
            
            #line 172 "..\..\..\Views\AdminCodeWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.NumberClicked);
            
            #line default
            #line hidden
            return;
            case 6:
            
            #line 173 "..\..\..\Views\AdminCodeWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.NumberClicked);
            
            #line default
            #line hidden
            return;
            case 7:
            
            #line 174 "..\..\..\Views\AdminCodeWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.NumberClicked);
            
            #line default
            #line hidden
            return;
            case 8:
            
            #line 175 "..\..\..\Views\AdminCodeWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.NumberClicked);
            
            #line default
            #line hidden
            return;
            case 9:
            
            #line 176 "..\..\..\Views\AdminCodeWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.NumberClicked);
            
            #line default
            #line hidden
            return;
            case 10:
            
            #line 177 "..\..\..\Views\AdminCodeWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.NumberClicked);
            
            #line default
            #line hidden
            return;
            case 11:
            
            #line 178 "..\..\..\Views\AdminCodeWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.NumberClicked);
            
            #line default
            #line hidden
            return;
            case 12:
            
            #line 179 "..\..\..\Views\AdminCodeWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.NumberClicked);
            
            #line default
            #line hidden
            return;
            case 13:
            
            #line 180 "..\..\..\Views\AdminCodeWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.NumberClicked);
            
            #line default
            #line hidden
            return;
            case 14:
            
            #line 181 "..\..\..\Views\AdminCodeWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.ClearClicked);
            
            #line default
            #line hidden
            return;
            case 15:
            
            #line 182 "..\..\..\Views\AdminCodeWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.NumberClicked);
            
            #line default
            #line hidden
            return;
            case 16:
            
            #line 183 "..\..\..\Views\AdminCodeWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.BackspaceClicked);
            
            #line default
            #line hidden
            return;
            case 17:
            
            #line 190 "..\..\..\Views\AdminCodeWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.ConfirmClicked);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

