#pragma checksum "..\..\..\Views\CodeVerificationWindow.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "7A803D0178AAAB6DF3B7F2FA3A4E32D4F23AFB7E"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using FFPOS.Controls;
using MaterialDesignThemes.Wpf;
using MaterialDesignThemes.Wpf.Converters;
using MaterialDesignThemes.Wpf.Transitions;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace FFPOS.Views {
    
    
    /// <summary>
    /// CodeVerificationWindow
    /// </summary>
    public partial class CodeVerificationWindow : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 92 "..\..\..\Views\CodeVerificationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock SentText;
        
        #line default
        #line hidden
        
        
        #line 93 "..\..\..\Views\CodeVerificationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock ExpiresText;
        
        #line default
        #line hidden
        
        
        #line 95 "..\..\..\Views\CodeVerificationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox Code1;
        
        #line default
        #line hidden
        
        
        #line 96 "..\..\..\Views\CodeVerificationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox Code2;
        
        #line default
        #line hidden
        
        
        #line 97 "..\..\..\Views\CodeVerificationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox Code3;
        
        #line default
        #line hidden
        
        
        #line 98 "..\..\..\Views\CodeVerificationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox Code4;
        
        #line default
        #line hidden
        
        
        #line 100 "..\..\..\Views\CodeVerificationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock ErrorText;
        
        #line default
        #line hidden
        
        
        #line 101 "..\..\..\Views\CodeVerificationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button VerifyButton;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.10.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/TIJORAT_PRO_POS;component/views/codeverificationwindow.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\Views\CodeVerificationWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.10.0")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal System.Delegate _CreateDelegate(System.Type delegateType, string handler) {
            return System.Delegate.CreateDelegate(delegateType, this, handler);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.10.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            
            #line 79 "..\..\..\Views\CodeVerificationWindow.xaml"
            ((System.Windows.Controls.Border)(target)).PreviewMouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.HeaderMouseLeftButtonDown);
            
            #line default
            #line hidden
            return;
            case 2:
            this.SentText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 3:
            this.ExpiresText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 4:
            this.Code1 = ((System.Windows.Controls.TextBox)(target));
            
            #line 95 "..\..\..\Views\CodeVerificationWindow.xaml"
            this.Code1.TextChanged += new System.Windows.Controls.TextChangedEventHandler(this.CodeTextChanged);
            
            #line default
            #line hidden
            
            #line 95 "..\..\..\Views\CodeVerificationWindow.xaml"
            this.Code1.PreviewTextInput += new System.Windows.Input.TextCompositionEventHandler(this.CodePreviewTextInput);
            
            #line default
            #line hidden
            
            #line 95 "..\..\..\Views\CodeVerificationWindow.xaml"
            this.Code1.PreviewKeyDown += new System.Windows.Input.KeyEventHandler(this.CodePreviewKeyDown);
            
            #line default
            #line hidden
            return;
            case 5:
            this.Code2 = ((System.Windows.Controls.TextBox)(target));
            
            #line 96 "..\..\..\Views\CodeVerificationWindow.xaml"
            this.Code2.TextChanged += new System.Windows.Controls.TextChangedEventHandler(this.CodeTextChanged);
            
            #line default
            #line hidden
            
            #line 96 "..\..\..\Views\CodeVerificationWindow.xaml"
            this.Code2.PreviewTextInput += new System.Windows.Input.TextCompositionEventHandler(this.CodePreviewTextInput);
            
            #line default
            #line hidden
            
            #line 96 "..\..\..\Views\CodeVerificationWindow.xaml"
            this.Code2.PreviewKeyDown += new System.Windows.Input.KeyEventHandler(this.CodePreviewKeyDown);
            
            #line default
            #line hidden
            return;
            case 6:
            this.Code3 = ((System.Windows.Controls.TextBox)(target));
            
            #line 97 "..\..\..\Views\CodeVerificationWindow.xaml"
            this.Code3.TextChanged += new System.Windows.Controls.TextChangedEventHandler(this.CodeTextChanged);
            
            #line default
            #line hidden
            
            #line 97 "..\..\..\Views\CodeVerificationWindow.xaml"
            this.Code3.PreviewTextInput += new System.Windows.Input.TextCompositionEventHandler(this.CodePreviewTextInput);
            
            #line default
            #line hidden
            
            #line 97 "..\..\..\Views\CodeVerificationWindow.xaml"
            this.Code3.PreviewKeyDown += new System.Windows.Input.KeyEventHandler(this.CodePreviewKeyDown);
            
            #line default
            #line hidden
            return;
            case 7:
            this.Code4 = ((System.Windows.Controls.TextBox)(target));
            
            #line 98 "..\..\..\Views\CodeVerificationWindow.xaml"
            this.Code4.TextChanged += new System.Windows.Controls.TextChangedEventHandler(this.CodeTextChanged);
            
            #line default
            #line hidden
            
            #line 98 "..\..\..\Views\CodeVerificationWindow.xaml"
            this.Code4.PreviewTextInput += new System.Windows.Input.TextCompositionEventHandler(this.CodePreviewTextInput);
            
            #line default
            #line hidden
            
            #line 98 "..\..\..\Views\CodeVerificationWindow.xaml"
            this.Code4.PreviewKeyDown += new System.Windows.Input.KeyEventHandler(this.CodePreviewKeyDown);
            
            #line default
            #line hidden
            return;
            case 8:
            this.ErrorText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 9:
            this.VerifyButton = ((System.Windows.Controls.Button)(target));
            
            #line 101 "..\..\..\Views\CodeVerificationWindow.xaml"
            this.VerifyButton.Click += new System.Windows.RoutedEventHandler(this.VerifyClicked);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

