#pragma checksum "..\..\..\Views\DdsOperationWindow.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "F951CDAA392192B617C8A3C11BB36842AF3CEE65"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using FFPOS.Controls;
using MaterialDesignThemes.Wpf;
using MaterialDesignThemes.Wpf.Converters;
using MaterialDesignThemes.Wpf.Transitions;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace FFPOS.Views {
    
    
    /// <summary>
    /// DdsOperationWindow
    /// </summary>
    public partial class DdsOperationWindow : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 351 "..\..\..\Views\DdsOperationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock TitleText;
        
        #line default
        #line hidden
        
        
        #line 364 "..\..\..\Views\DdsOperationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel CustomerPanel;
        
        #line default
        #line hidden
        
        
        #line 373 "..\..\..\Views\DdsOperationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock CustomerText;
        
        #line default
        #line hidden
        
        
        #line 374 "..\..\..\Views\DdsOperationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock CustomerBalanceText;
        
        #line default
        #line hidden
        
        
        #line 387 "..\..\..\Views\DdsOperationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox CashBox;
        
        #line default
        #line hidden
        
        
        #line 390 "..\..\..\Views\DdsOperationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox ArticleBox;
        
        #line default
        #line hidden
        
        
        #line 394 "..\..\..\Views\DdsOperationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border DirectionBadge;
        
        #line default
        #line hidden
        
        
        #line 395 "..\..\..\Views\DdsOperationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock DirectionText;
        
        #line default
        #line hidden
        
        
        #line 399 "..\..\..\Views\DdsOperationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox AmountBox;
        
        #line default
        #line hidden
        
        
        #line 403 "..\..\..\Views\DdsOperationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox DescriptionBox;
        
        #line default
        #line hidden
        
        
        #line 407 "..\..\..\Views\DdsOperationWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock ErrorText;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.10.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/TIJORAT_PRO_POS;component/views/ddsoperationwindow.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\Views\DdsOperationWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.10.0")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal System.Delegate _CreateDelegate(System.Type delegateType, string handler) {
            return System.Delegate.CreateDelegate(delegateType, this, handler);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.10.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            
            #line 347 "..\..\..\Views\DdsOperationWindow.xaml"
            ((System.Windows.Controls.Border)(target)).MouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.HeaderMouseLeftButtonDown);
            
            #line default
            #line hidden
            return;
            case 2:
            this.TitleText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 3:
            this.CustomerPanel = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 4:
            this.CustomerText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 5:
            this.CustomerBalanceText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 6:
            
            #line 376 "..\..\..\Views\DdsOperationWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.SelectCustomerClicked);
            
            #line default
            #line hidden
            return;
            case 7:
            this.CashBox = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 8:
            this.ArticleBox = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 9:
            this.DirectionBadge = ((System.Windows.Controls.Border)(target));
            return;
            case 10:
            this.DirectionText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 11:
            this.AmountBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 12:
            this.DescriptionBox = ((System.Windows.Controls.TextBox)(target));
            
            #line 405 "..\..\..\Views\DdsOperationWindow.xaml"
            this.DescriptionBox.TextChanged += new System.Windows.Controls.TextChangedEventHandler(this.DescriptionBox_OnTextChanged);
            
            #line default
            #line hidden
            return;
            case 13:
            this.ErrorText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 14:
            
            #line 417 "..\..\..\Views\DdsOperationWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.AmountKeypadClicked);
            
            #line default
            #line hidden
            return;
            case 15:
            
            #line 418 "..\..\..\Views\DdsOperationWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.AmountKeypadClicked);
            
            #line default
            #line hidden
            return;
            case 16:
            
            #line 419 "..\..\..\Views\DdsOperationWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.AmountKeypadClicked);
            
            #line default
            #line hidden
            return;
            case 17:
            
            #line 420 "..\..\..\Views\DdsOperationWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.AmountKeypadClicked);
            
            #line default
            #line hidden
            return;
            case 18:
            
            #line 421 "..\..\..\Views\DdsOperationWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.AmountKeypadClicked);
            
            #line default
            #line hidden
            return;
            case 19:
            
            #line 422 "..\..\..\Views\DdsOperationWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.AmountKeypadClicked);
            
            #line default
            #line hidden
            return;
            case 20:
            
            #line 423 "..\..\..\Views\DdsOperationWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.AmountKeypadClicked);
            
            #line default
            #line hidden
            return;
            case 21:
            
            #line 424 "..\..\..\Views\DdsOperationWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.AmountKeypadClicked);
            
            #line default
            #line hidden
            return;
            case 22:
            
            #line 425 "..\..\..\Views\DdsOperationWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.AmountKeypadClicked);
            
            #line default
            #line hidden
            return;
            case 23:
            
            #line 426 "..\..\..\Views\DdsOperationWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.AmountKeypadClicked);
            
            #line default
            #line hidden
            return;
            case 24:
            
            #line 427 "..\..\..\Views\DdsOperationWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.AmountKeypadClicked);
            
            #line default
            #line hidden
            return;
            case 25:
            
            #line 428 "..\..\..\Views\DdsOperationWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.AmountBackspaceClicked);
            
            #line default
            #line hidden
            return;
            case 26:
            
            #line 437 "..\..\..\Views\DdsOperationWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.CancelClicked);
            
            #line default
            #line hidden
            return;
            case 27:
            
            #line 438 "..\..\..\Views\DdsOperationWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.SaveClicked);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

