#pragma checksum "..\..\..\Views\LoginWindow.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "94B0FBEA42DC5E0A8F1E2933D53A926A2624A150"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using FFPOS.Controls;
using MaterialDesignThemes.Wpf;
using MaterialDesignThemes.Wpf.Converters;
using MaterialDesignThemes.Wpf.Transitions;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace FFPOS.Views {
    
    
    /// <summary>
    /// LoginWindow
    /// </summary>
    public partial class LoginWindow : System.Windows.Window, System.Windows.Markup.IComponentConnector, System.Windows.Markup.IStyleConnector {
        
        
        #line 327 "..\..\..\Views\LoginWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid ContentGrid;
        
        #line default
        #line hidden
        
        
        #line 329 "..\..\..\Views\LoginWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ColumnDefinition FormColumn;
        
        #line default
        #line hidden
        
        
        #line 330 "..\..\..\Views\LoginWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ColumnDefinition SpacerColumn;
        
        #line default
        #line hidden
        
        
        #line 331 "..\..\..\Views\LoginWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ColumnDefinition KeypadColumn;
        
        #line default
        #line hidden
        
        
        #line 335 "..\..\..\Views\LoginWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid FormPanel;
        
        #line default
        #line hidden
        
        
        #line 364 "..\..\..\Views\LoginWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox LoginBox;
        
        #line default
        #line hidden
        
        
        #line 370 "..\..\..\Views\LoginWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock LoginPlaceholder;
        
        #line default
        #line hidden
        
        
        #line 392 "..\..\..\Views\LoginWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.PasswordBox PasswordBox;
        
        #line default
        #line hidden
        
        
        #line 396 "..\..\..\Views\LoginWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox VisiblePasswordBox;
        
        #line default
        #line hidden
        
        
        #line 401 "..\..\..\Views\LoginWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock PasswordPlaceholder;
        
        #line default
        #line hidden
        
        
        #line 415 "..\..\..\Views\LoginWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal MaterialDesignThemes.Wpf.PackIcon PasswordEyeIcon;
        
        #line default
        #line hidden
        
        
        #line 438 "..\..\..\Views\LoginWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock AppNameText;
        
        #line default
        #line hidden
        
        
        #line 439 "..\..\..\Views\LoginWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock ErrorText;
        
        #line default
        #line hidden
        
        
        #line 449 "..\..\..\Views\LoginWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Viewbox KeypadPanel;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.10.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/TIJORAT_PRO_POS;component/views/loginwindow.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\Views\LoginWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.10.0")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal System.Delegate _CreateDelegate(System.Type delegateType, string handler) {
            return System.Delegate.CreateDelegate(delegateType, this, handler);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.10.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            
            #line 17 "..\..\..\Views\LoginWindow.xaml"
            ((FFPOS.Views.LoginWindow)(target)).KeyDown += new System.Windows.Input.KeyEventHandler(this.WindowKeyDown);
            
            #line default
            #line hidden
            
            #line 18 "..\..\..\Views\LoginWindow.xaml"
            ((FFPOS.Views.LoginWindow)(target)).SizeChanged += new System.Windows.SizeChangedEventHandler(this.WindowSizeChanged);
            
            #line default
            #line hidden
            
            #line 19 "..\..\..\Views\LoginWindow.xaml"
            ((FFPOS.Views.LoginWindow)(target)).Loaded += new System.Windows.RoutedEventHandler(this.WindowLoaded);
            
            #line default
            #line hidden
            return;
            case 3:
            
            #line 308 "..\..\..\Views\LoginWindow.xaml"
            ((System.Windows.Controls.Border)(target)).PreviewMouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.HeaderMouseLeftButtonDown);
            
            #line default
            #line hidden
            return;
            case 4:
            this.ContentGrid = ((System.Windows.Controls.Grid)(target));
            return;
            case 5:
            this.FormColumn = ((System.Windows.Controls.ColumnDefinition)(target));
            return;
            case 6:
            this.SpacerColumn = ((System.Windows.Controls.ColumnDefinition)(target));
            return;
            case 7:
            this.KeypadColumn = ((System.Windows.Controls.ColumnDefinition)(target));
            return;
            case 8:
            this.FormPanel = ((System.Windows.Controls.Grid)(target));
            return;
            case 9:
            this.LoginBox = ((System.Windows.Controls.ComboBox)(target));
            
            #line 367 "..\..\..\Views\LoginWindow.xaml"
            this.LoginBox.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.LoginSelectionChanged);
            
            #line default
            #line hidden
            
            #line 368 "..\..\..\Views\LoginWindow.xaml"
            this.LoginBox.PreviewGotKeyboardFocus += new System.Windows.Input.KeyboardFocusChangedEventHandler(this.LoginBoxPreviewGotKeyboardFocus);
            
            #line default
            #line hidden
            return;
            case 10:
            this.LoginPlaceholder = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 11:
            this.PasswordBox = ((System.Windows.Controls.PasswordBox)(target));
            
            #line 395 "..\..\..\Views\LoginWindow.xaml"
            this.PasswordBox.PasswordChanged += new System.Windows.RoutedEventHandler(this.PasswordChanged);
            
            #line default
            #line hidden
            return;
            case 12:
            this.VisiblePasswordBox = ((System.Windows.Controls.TextBox)(target));
            
            #line 400 "..\..\..\Views\LoginWindow.xaml"
            this.VisiblePasswordBox.TextChanged += new System.Windows.Controls.TextChangedEventHandler(this.VisiblePasswordChanged);
            
            #line default
            #line hidden
            return;
            case 13:
            this.PasswordPlaceholder = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 14:
            
            #line 414 "..\..\..\Views\LoginWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.TogglePasswordClicked);
            
            #line default
            #line hidden
            return;
            case 15:
            this.PasswordEyeIcon = ((MaterialDesignThemes.Wpf.PackIcon)(target));
            return;
            case 16:
            this.AppNameText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 17:
            this.ErrorText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 18:
            
            #line 440 "..\..\..\Views\LoginWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.LoginClicked);
            
            #line default
            #line hidden
            return;
            case 19:
            this.KeypadPanel = ((System.Windows.Controls.Viewbox)(target));
            return;
            case 20:
            
            #line 451 "..\..\..\Views\LoginWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.NumberKeyClicked);
            
            #line default
            #line hidden
            return;
            case 21:
            
            #line 452 "..\..\..\Views\LoginWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.NumberKeyClicked);
            
            #line default
            #line hidden
            return;
            case 22:
            
            #line 453 "..\..\..\Views\LoginWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.NumberKeyClicked);
            
            #line default
            #line hidden
            return;
            case 23:
            
            #line 454 "..\..\..\Views\LoginWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.NumberKeyClicked);
            
            #line default
            #line hidden
            return;
            case 24:
            
            #line 455 "..\..\..\Views\LoginWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.NumberKeyClicked);
            
            #line default
            #line hidden
            return;
            case 25:
            
            #line 456 "..\..\..\Views\LoginWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.NumberKeyClicked);
            
            #line default
            #line hidden
            return;
            case 26:
            
            #line 457 "..\..\..\Views\LoginWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.NumberKeyClicked);
            
            #line default
            #line hidden
            return;
            case 27:
            
            #line 458 "..\..\..\Views\LoginWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.NumberKeyClicked);
            
            #line default
            #line hidden
            return;
            case 28:
            
            #line 459 "..\..\..\Views\LoginWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.NumberKeyClicked);
            
            #line default
            #line hidden
            return;
            case 29:
            
            #line 460 "..\..\..\Views\LoginWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.ClearPasswordClicked);
            
            #line default
            #line hidden
            return;
            case 30:
            
            #line 461 "..\..\..\Views\LoginWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.NumberKeyClicked);
            
            #line default
            #line hidden
            return;
            case 31:
            
            #line 462 "..\..\..\Views\LoginWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.BackspaceClicked);
            
            #line default
            #line hidden
            return;
            case 32:
            
            #line 471 "..\..\..\Views\LoginWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.OpenKeyboardClicked);
            
            #line default
            #line hidden
            return;
            case 33:
            
            #line 479 "..\..\..\Views\LoginWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.OpenSyncClicked);
            
            #line default
            #line hidden
            return;
            case 34:
            
            #line 483 "..\..\..\Views\LoginWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.OpenSettingsClicked);
            
            #line default
            #line hidden
            return;
            case 35:
            
            #line 487 "..\..\..\Views\LoginWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.OpenSettingsClicked);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.10.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        void System.Windows.Markup.IStyleConnector.Connect(int connectionId, object target) {
            System.Windows.EventSetter eventSetter;
            switch (connectionId)
            {
            case 2:
            eventSetter = new System.Windows.EventSetter();
            eventSetter.Event = System.Windows.UIElement.PreviewMouseLeftButtonUpEvent;
            
            #line 100 "..\..\..\Views\LoginWindow.xaml"
            eventSetter.Handler = new System.Windows.Input.MouseButtonEventHandler(this.LoginComboItemPreviewMouseLeftButtonUp);
            
            #line default
            #line hidden
            ((System.Windows.Style)(target)).Setters.Add(eventSetter);
            break;
            }
        }
    }
}

