#pragma checksum "..\..\..\Views\OrderValueInputWindow.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "0DD8115E365E87BD31A0B75816EC97F3D10865D7"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using MaterialDesignThemes.Wpf;
using MaterialDesignThemes.Wpf.Converters;
using MaterialDesignThemes.Wpf.Transitions;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace FFPOS.Views {
    
    
    /// <summary>
    /// OrderValueInputWindow
    /// </summary>
    public partial class OrderValueInputWindow : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 91 "..\..\..\Views\OrderValueInputWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock TitleText;
        
        #line default
        #line hidden
        
        
        #line 120 "..\..\..\Views\OrderValueInputWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock PromptText;
        
        #line default
        #line hidden
        
        
        #line 131 "..\..\..\Views\OrderValueInputWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox ValueBox;
        
        #line default
        #line hidden
        
        
        #line 168 "..\..\..\Views\OrderValueInputWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button DotButton;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.10.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/TIJORAT_PRO_POS;component/views/ordervalueinputwindow.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\Views\OrderValueInputWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.10.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            
            #line 89 "..\..\..\Views\OrderValueInputWindow.xaml"
            ((System.Windows.Controls.Border)(target)).MouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.HeaderMouseLeftButtonDown);
            
            #line default
            #line hidden
            return;
            case 2:
            this.TitleText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 3:
            
            #line 103 "..\..\..\Views\OrderValueInputWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.CancelClicked);
            
            #line default
            #line hidden
            return;
            case 4:
            this.PromptText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 5:
            this.ValueBox = ((System.Windows.Controls.TextBox)(target));
            
            #line 140 "..\..\..\Views\OrderValueInputWindow.xaml"
            this.ValueBox.TextChanged += new System.Windows.Controls.TextChangedEventHandler(this.ValueBoxTextChanged);
            
            #line default
            #line hidden
            return;
            case 6:
            
            #line 156 "..\..\..\Views\OrderValueInputWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.KeypadClicked);
            
            #line default
            #line hidden
            return;
            case 7:
            
            #line 157 "..\..\..\Views\OrderValueInputWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.KeypadClicked);
            
            #line default
            #line hidden
            return;
            case 8:
            
            #line 158 "..\..\..\Views\OrderValueInputWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.KeypadClicked);
            
            #line default
            #line hidden
            return;
            case 9:
            
            #line 160 "..\..\..\Views\OrderValueInputWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.KeypadClicked);
            
            #line default
            #line hidden
            return;
            case 10:
            
            #line 161 "..\..\..\Views\OrderValueInputWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.KeypadClicked);
            
            #line default
            #line hidden
            return;
            case 11:
            
            #line 162 "..\..\..\Views\OrderValueInputWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.KeypadClicked);
            
            #line default
            #line hidden
            return;
            case 12:
            
            #line 164 "..\..\..\Views\OrderValueInputWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.KeypadClicked);
            
            #line default
            #line hidden
            return;
            case 13:
            
            #line 165 "..\..\..\Views\OrderValueInputWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.KeypadClicked);
            
            #line default
            #line hidden
            return;
            case 14:
            
            #line 166 "..\..\..\Views\OrderValueInputWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.KeypadClicked);
            
            #line default
            #line hidden
            return;
            case 15:
            this.DotButton = ((System.Windows.Controls.Button)(target));
            
            #line 168 "..\..\..\Views\OrderValueInputWindow.xaml"
            this.DotButton.Click += new System.Windows.RoutedEventHandler(this.KeypadClicked);
            
            #line default
            #line hidden
            return;
            case 16:
            
            #line 169 "..\..\..\Views\OrderValueInputWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.KeypadClicked);
            
            #line default
            #line hidden
            return;
            case 17:
            
            #line 170 "..\..\..\Views\OrderValueInputWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.BackspaceClicked);
            
            #line default
            #line hidden
            return;
            case 18:
            
            #line 181 "..\..\..\Views\OrderValueInputWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.CancelClicked);
            
            #line default
            #line hidden
            return;
            case 19:
            
            #line 182 "..\..\..\Views\OrderValueInputWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.OkClicked);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

