#pragma checksum "..\..\..\Views\PaymentWindow.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "28F5A27CCFF9B9634BBA0A85D9C722E20F6FBAEB"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using FFPOS.Controls;
using MaterialDesignThemes.Wpf;
using MaterialDesignThemes.Wpf.Converters;
using MaterialDesignThemes.Wpf.Transitions;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace FFPOS.Views {
    
    
    /// <summary>
    /// PaymentWindow
    /// </summary>
    public partial class PaymentWindow : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 399 "..\..\..\Views\PaymentWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button CustomerButton;
        
        #line default
        #line hidden
        
        
        #line 405 "..\..\..\Views\PaymentWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock CustomerText;
        
        #line default
        #line hidden
        
        
        #line 411 "..\..\..\Views\PaymentWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TotalBox;
        
        #line default
        #line hidden
        
        
        #line 424 "..\..\..\Views\PaymentWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox DiscountPercentBox;
        
        #line default
        #line hidden
        
        
        #line 431 "..\..\..\Views\PaymentWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox DiscountAmountBox;
        
        #line default
        #line hidden
        
        
        #line 437 "..\..\..\Views\PaymentWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox PayableBox;
        
        #line default
        #line hidden
        
        
        #line 440 "..\..\..\Views\PaymentWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox NoteBox;
        
        #line default
        #line hidden
        
        
        #line 443 "..\..\..\Views\PaymentWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border PaymentsCard;
        
        #line default
        #line hidden
        
        
        #line 456 "..\..\..\Views\PaymentWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button AddPaymentButton;
        
        #line default
        #line hidden
        
        
        #line 467 "..\..\..\Views\PaymentWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ScrollViewer PaymentRowsScrollViewer;
        
        #line default
        #line hidden
        
        
        #line 474 "..\..\..\Views\PaymentWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel PaymentRowsPanel;
        
        #line default
        #line hidden
        
        
        #line 475 "..\..\..\Views\PaymentWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid FirstPaymentRow;
        
        #line default
        #line hidden
        
        
        #line 485 "..\..\..\Views\PaymentWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox CashAccountBox;
        
        #line default
        #line hidden
        
        
        #line 492 "..\..\..\Views\PaymentWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox CashPaymentBox;
        
        #line default
        #line hidden
        
        
        #line 511 "..\..\..\Views\PaymentWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock ReceivedText;
        
        #line default
        #line hidden
        
        
        #line 512 "..\..\..\Views\PaymentWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock RemainderLabel;
        
        #line default
        #line hidden
        
        
        #line 513 "..\..\..\Views\PaymentWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock RemainderText;
        
        #line default
        #line hidden
        
        
        #line 531 "..\..\..\Views\PaymentWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid OrderTypeGrid;
        
        #line default
        #line hidden
        
        
        #line 532 "..\..\..\Views\PaymentWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button DineInButton;
        
        #line default
        #line hidden
        
        
        #line 537 "..\..\..\Views\PaymentWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button TakeAwayButton;
        
        #line default
        #line hidden
        
        
        #line 542 "..\..\..\Views\PaymentWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button DeliveryButton;
        
        #line default
        #line hidden
        
        
        #line 581 "..\..\..\Views\PaymentWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button QuickAmount1Button;
        
        #line default
        #line hidden
        
        
        #line 582 "..\..\..\Views\PaymentWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button QuickAmount2Button;
        
        #line default
        #line hidden
        
        
        #line 583 "..\..\..\Views\PaymentWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button QuickAmount3Button;
        
        #line default
        #line hidden
        
        
        #line 588 "..\..\..\Views\PaymentWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox PrintReceiptBox;
        
        #line default
        #line hidden
        
        
        #line 607 "..\..\..\Views\PaymentWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ConfirmButton;
        
        #line default
        #line hidden
        
        
        #line 610 "..\..\..\Views\PaymentWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock ConfirmButtonText;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.10.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/TIJORAT_PRO_POS;component/views/paymentwindow.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\Views\PaymentWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.10.0")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal System.Delegate _CreateDelegate(System.Type delegateType, string handler) {
            return System.Delegate.CreateDelegate(delegateType, this, handler);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.10.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            
            #line 361 "..\..\..\Views\PaymentWindow.xaml"
            ((System.Windows.Controls.Border)(target)).MouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.HeaderMouseLeftButtonDown);
            
            #line default
            #line hidden
            return;
            case 2:
            this.CustomerButton = ((System.Windows.Controls.Button)(target));
            
            #line 399 "..\..\..\Views\PaymentWindow.xaml"
            this.CustomerButton.Click += new System.Windows.RoutedEventHandler(this.CustomerClicked);
            
            #line default
            #line hidden
            return;
            case 3:
            this.CustomerText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 4:
            this.TotalBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 5:
            this.DiscountPercentBox = ((System.Windows.Controls.TextBox)(target));
            
            #line 424 "..\..\..\Views\PaymentWindow.xaml"
            this.DiscountPercentBox.TextChanged += new System.Windows.Controls.TextChangedEventHandler(this.DiscountPercentChanged);
            
            #line default
            #line hidden
            
            #line 424 "..\..\..\Views\PaymentWindow.xaml"
            this.DiscountPercentBox.GotFocus += new System.Windows.RoutedEventHandler(this.DiscountPercentFocused);
            
            #line default
            #line hidden
            return;
            case 6:
            this.DiscountAmountBox = ((System.Windows.Controls.TextBox)(target));
            
            #line 431 "..\..\..\Views\PaymentWindow.xaml"
            this.DiscountAmountBox.TextChanged += new System.Windows.Controls.TextChangedEventHandler(this.DiscountAmountChanged);
            
            #line default
            #line hidden
            
            #line 431 "..\..\..\Views\PaymentWindow.xaml"
            this.DiscountAmountBox.GotFocus += new System.Windows.RoutedEventHandler(this.DiscountAmountFocused);
            
            #line default
            #line hidden
            return;
            case 7:
            this.PayableBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 8:
            this.NoteBox = ((System.Windows.Controls.TextBox)(target));
            
            #line 440 "..\..\..\Views\PaymentWindow.xaml"
            this.NoteBox.GotFocus += new System.Windows.RoutedEventHandler(this.NoteFocused);
            
            #line default
            #line hidden
            return;
            case 9:
            this.PaymentsCard = ((System.Windows.Controls.Border)(target));
            return;
            case 10:
            this.AddPaymentButton = ((System.Windows.Controls.Button)(target));
            
            #line 456 "..\..\..\Views\PaymentWindow.xaml"
            this.AddPaymentButton.Click += new System.Windows.RoutedEventHandler(this.AddPaymentClicked);
            
            #line default
            #line hidden
            return;
            case 11:
            this.PaymentRowsScrollViewer = ((System.Windows.Controls.ScrollViewer)(target));
            return;
            case 12:
            this.PaymentRowsPanel = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 13:
            this.FirstPaymentRow = ((System.Windows.Controls.Grid)(target));
            return;
            case 14:
            
            #line 482 "..\..\..\Views\PaymentWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.ClearCashClicked);
            
            #line default
            #line hidden
            return;
            case 15:
            this.CashAccountBox = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 16:
            this.CashPaymentBox = ((System.Windows.Controls.TextBox)(target));
            
            #line 492 "..\..\..\Views\PaymentWindow.xaml"
            this.CashPaymentBox.GotFocus += new System.Windows.RoutedEventHandler(this.CashPaymentFocused);
            
            #line default
            #line hidden
            
            #line 492 "..\..\..\Views\PaymentWindow.xaml"
            this.CashPaymentBox.TextChanged += new System.Windows.Controls.TextChangedEventHandler(this.PaymentAmountChanged);
            
            #line default
            #line hidden
            return;
            case 17:
            this.ReceivedText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 18:
            this.RemainderLabel = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 19:
            this.RemainderText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 20:
            this.OrderTypeGrid = ((System.Windows.Controls.Grid)(target));
            return;
            case 21:
            this.DineInButton = ((System.Windows.Controls.Button)(target));
            
            #line 536 "..\..\..\Views\PaymentWindow.xaml"
            this.DineInButton.Click += new System.Windows.RoutedEventHandler(this.OrderTypeClicked);
            
            #line default
            #line hidden
            return;
            case 22:
            this.TakeAwayButton = ((System.Windows.Controls.Button)(target));
            
            #line 541 "..\..\..\Views\PaymentWindow.xaml"
            this.TakeAwayButton.Click += new System.Windows.RoutedEventHandler(this.OrderTypeClicked);
            
            #line default
            #line hidden
            return;
            case 23:
            this.DeliveryButton = ((System.Windows.Controls.Button)(target));
            
            #line 546 "..\..\..\Views\PaymentWindow.xaml"
            this.DeliveryButton.Click += new System.Windows.RoutedEventHandler(this.OrderTypeClicked);
            
            #line default
            #line hidden
            return;
            case 24:
            
            #line 562 "..\..\..\Views\PaymentWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.NumberClicked);
            
            #line default
            #line hidden
            return;
            case 25:
            
            #line 563 "..\..\..\Views\PaymentWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.NumberClicked);
            
            #line default
            #line hidden
            return;
            case 26:
            
            #line 564 "..\..\..\Views\PaymentWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.NumberClicked);
            
            #line default
            #line hidden
            return;
            case 27:
            
            #line 565 "..\..\..\Views\PaymentWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.NumberClicked);
            
            #line default
            #line hidden
            return;
            case 28:
            
            #line 566 "..\..\..\Views\PaymentWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.NumberClicked);
            
            #line default
            #line hidden
            return;
            case 29:
            
            #line 567 "..\..\..\Views\PaymentWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.NumberClicked);
            
            #line default
            #line hidden
            return;
            case 30:
            
            #line 568 "..\..\..\Views\PaymentWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.NumberClicked);
            
            #line default
            #line hidden
            return;
            case 31:
            
            #line 569 "..\..\..\Views\PaymentWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.NumberClicked);
            
            #line default
            #line hidden
            return;
            case 32:
            
            #line 570 "..\..\..\Views\PaymentWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.NumberClicked);
            
            #line default
            #line hidden
            return;
            case 33:
            
            #line 571 "..\..\..\Views\PaymentWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.NumberClicked);
            
            #line default
            #line hidden
            return;
            case 34:
            
            #line 572 "..\..\..\Views\PaymentWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.NumberClicked);
            
            #line default
            #line hidden
            return;
            case 35:
            
            #line 573 "..\..\..\Views\PaymentWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.BackspaceClicked);
            
            #line default
            #line hidden
            return;
            case 36:
            this.QuickAmount1Button = ((System.Windows.Controls.Button)(target));
            
            #line 581 "..\..\..\Views\PaymentWindow.xaml"
            this.QuickAmount1Button.Click += new System.Windows.RoutedEventHandler(this.QuickAmountClicked);
            
            #line default
            #line hidden
            return;
            case 37:
            this.QuickAmount2Button = ((System.Windows.Controls.Button)(target));
            
            #line 582 "..\..\..\Views\PaymentWindow.xaml"
            this.QuickAmount2Button.Click += new System.Windows.RoutedEventHandler(this.QuickAmountClicked);
            
            #line default
            #line hidden
            return;
            case 38:
            this.QuickAmount3Button = ((System.Windows.Controls.Button)(target));
            
            #line 583 "..\..\..\Views\PaymentWindow.xaml"
            this.QuickAmount3Button.Click += new System.Windows.RoutedEventHandler(this.QuickAmountClicked);
            
            #line default
            #line hidden
            return;
            case 39:
            this.PrintReceiptBox = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 40:
            
            #line 601 "..\..\..\Views\PaymentWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.HoldClicked);
            
            #line default
            #line hidden
            return;
            case 41:
            this.ConfirmButton = ((System.Windows.Controls.Button)(target));
            
            #line 607 "..\..\..\Views\PaymentWindow.xaml"
            this.ConfirmButton.Click += new System.Windows.RoutedEventHandler(this.ConfirmClicked);
            
            #line default
            #line hidden
            return;
            case 42:
            this.ConfirmButtonText = ((System.Windows.Controls.TextBlock)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

