#pragma checksum "..\..\..\Views\SalesView.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "3140AAD87D873ADE347DAD5A47A3D93870B5A401"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using FFPOS.Controls;
using FFPOS.Converters;
using MaterialDesignThemes.Wpf;
using MaterialDesignThemes.Wpf.Converters;
using MaterialDesignThemes.Wpf.Transitions;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace FFPOS.Views {
    
    
    /// <summary>
    /// SalesView
    /// </summary>
    public partial class SalesView : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 534 "..\..\..\Views\SalesView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ProfileButton;
        
        #line default
        #line hidden
        
        
        #line 550 "..\..\..\Views\SalesView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Primitives.Popup ProfilePopup;
        
        #line default
        #line hidden
        
        
        #line 636 "..\..\..\Views\SalesView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TopSearchBox;
        
        #line default
        #line hidden
        
        
        #line 690 "..\..\..\Views\SalesView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox SearchBox;
        
        #line default
        #line hidden
        
        
        #line 881 "..\..\..\Views\SalesView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button OrderActionsButton;
        
        #line default
        #line hidden
        
        
        #line 884 "..\..\..\Views\SalesView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Primitives.Popup OrderActionsPopup;
        
        #line default
        #line hidden
        
        
        #line 942 "..\..\..\Views\SalesView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ScrollViewer ReceiptItemsScrollViewer;
        
        #line default
        #line hidden
        
        
        #line 943 "..\..\..\Views\SalesView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ItemsControl ReceiptItemsControl;
        
        #line default
        #line hidden
        
        
        #line 1002 "..\..\..\Views\SalesView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox OrderSearchBox;
        
        #line default
        #line hidden
        
        
        #line 1339 "..\..\..\Views\SalesView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox PaymentSearchBox;
        
        #line default
        #line hidden
        
        
        #line 1386 "..\..\..\Views\SalesView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button PaymentActionsButton;
        
        #line default
        #line hidden
        
        
        #line 1393 "..\..\..\Views\SalesView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Primitives.Popup PaymentActionsPopup;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.10.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/TIJORAT_PRO_POS;component/views/salesview.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\Views\SalesView.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.10.0")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal System.Delegate _CreateDelegate(System.Type delegateType, string handler) {
            return System.Delegate.CreateDelegate(delegateType, this, handler);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.10.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            
            #line 465 "..\..\..\Views\SalesView.xaml"
            ((System.Windows.Controls.Border)(target)).MouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.HeaderMouseLeftButtonDown);
            
            #line default
            #line hidden
            return;
            case 2:
            this.ProfileButton = ((System.Windows.Controls.Button)(target));
            
            #line 534 "..\..\..\Views\SalesView.xaml"
            this.ProfileButton.Click += new System.Windows.RoutedEventHandler(this.ProfileButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 3:
            this.ProfilePopup = ((System.Windows.Controls.Primitives.Popup)(target));
            return;
            case 4:
            this.TopSearchBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 5:
            this.SearchBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 6:
            this.OrderActionsButton = ((System.Windows.Controls.Button)(target));
            
            #line 881 "..\..\..\Views\SalesView.xaml"
            this.OrderActionsButton.Click += new System.Windows.RoutedEventHandler(this.OrderActionsButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 7:
            this.OrderActionsPopup = ((System.Windows.Controls.Primitives.Popup)(target));
            return;
            case 8:
            this.ReceiptItemsScrollViewer = ((System.Windows.Controls.ScrollViewer)(target));
            return;
            case 9:
            this.ReceiptItemsControl = ((System.Windows.Controls.ItemsControl)(target));
            return;
            case 10:
            this.OrderSearchBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 11:
            this.PaymentSearchBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 12:
            this.PaymentActionsButton = ((System.Windows.Controls.Button)(target));
            
            #line 1386 "..\..\..\Views\SalesView.xaml"
            this.PaymentActionsButton.Click += new System.Windows.RoutedEventHandler(this.PaymentActionsButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 13:
            this.PaymentActionsPopup = ((System.Windows.Controls.Primitives.Popup)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

