#pragma checksum "..\..\..\Views\SettingsWindow.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "7DC75F03826EAAA7413871BFF32655A02190E6BD"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using FFPOS.Controls;
using MaterialDesignThemes.Wpf;
using MaterialDesignThemes.Wpf.Converters;
using MaterialDesignThemes.Wpf.Transitions;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace FFPOS.Views {
    
    
    /// <summary>
    /// SettingsWindow
    /// </summary>
    public partial class SettingsWindow : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 292 "..\..\..\Views\SettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock HeaderSubtitle;
        
        #line default
        #line hidden
        
        
        #line 321 "..\..\..\Views\SettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal FFPOS.Controls.SettingTextField BaseUrlBox;
        
        #line default
        #line hidden
        
        
        #line 322 "..\..\..\Views\SettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal FFPOS.Controls.SettingTextField PublicUrlBox;
        
        #line default
        #line hidden
        
        
        #line 323 "..\..\..\Views\SettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal FFPOS.Controls.SettingTextField StoreNameBox;
        
        #line default
        #line hidden
        
        
        #line 324 "..\..\..\Views\SettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal FFPOS.Controls.SettingTextField StorePhoneBox;
        
        #line default
        #line hidden
        
        
        #line 325 "..\..\..\Views\SettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal FFPOS.Controls.SettingTextField AppDateBox;
        
        #line default
        #line hidden
        
        
        #line 326 "..\..\..\Views\SettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal FFPOS.Controls.SettingTextField AppStatusTextBox;
        
        #line default
        #line hidden
        
        
        #line 336 "..\..\..\Views\SettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox StoreSelectBox;
        
        #line default
        #line hidden
        
        
        #line 350 "..\..\..\Views\SettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border StoreDetailsPanel;
        
        #line default
        #line hidden
        
        
        #line 381 "..\..\..\Views\SettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal FFPOS.Controls.SettingTextField StoreNameInfoBox;
        
        #line default
        #line hidden
        
        
        #line 382 "..\..\..\Views\SettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal FFPOS.Controls.SettingTextField StoreAgelNameBox;
        
        #line default
        #line hidden
        
        
        #line 383 "..\..\..\Views\SettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal FFPOS.Controls.SettingTextField StoreLocationBox;
        
        #line default
        #line hidden
        
        
        #line 384 "..\..\..\Views\SettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal FFPOS.Controls.SettingTextField StorePhoneInfoBox;
        
        #line default
        #line hidden
        
        
        #line 385 "..\..\..\Views\SettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal FFPOS.Controls.SettingTextField StoreEmailBox;
        
        #line default
        #line hidden
        
        
        #line 386 "..\..\..\Views\SettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal FFPOS.Controls.SettingTextField StoreSiteBox;
        
        #line default
        #line hidden
        
        
        #line 387 "..\..\..\Views\SettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal FFPOS.Controls.SettingTextField StoreDescriptionBox;
        
        #line default
        #line hidden
        
        
        #line 398 "..\..\..\Views\SettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal FFPOS.Controls.SettingChoiceField DatabaseTypeBox;
        
        #line default
        #line hidden
        
        
        #line 404 "..\..\..\Views\SettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel SqliteDetailsPanel;
        
        #line default
        #line hidden
        
        
        #line 405 "..\..\..\Views\SettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal FFPOS.Controls.SettingTextField SQLitePathBox;
        
        #line default
        #line hidden
        
        
        #line 411 "..\..\..\Views\SettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border MySqlDetailsPanel;
        
        #line default
        #line hidden
        
        
        #line 439 "..\..\..\Views\SettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal FFPOS.Controls.SettingTextField MySqlHostBox;
        
        #line default
        #line hidden
        
        
        #line 440 "..\..\..\Views\SettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal FFPOS.Controls.SettingTextField MySqlPortBox;
        
        #line default
        #line hidden
        
        
        #line 441 "..\..\..\Views\SettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal FFPOS.Controls.SettingTextField MySqlDatabaseBox;
        
        #line default
        #line hidden
        
        
        #line 442 "..\..\..\Views\SettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal FFPOS.Controls.SettingTextField MySqlUsernameBox;
        
        #line default
        #line hidden
        
        
        #line 443 "..\..\..\Views\SettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal FFPOS.Controls.SettingTextField MySqlPasswordBox;
        
        #line default
        #line hidden
        
        
        #line 446 "..\..\..\Views\SettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button TestMySqlButton;
        
        #line default
        #line hidden
        
        
        #line 503 "..\..\..\Views\SettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal FFPOS.Controls.SettingToggleField IsTouchScreenBox;
        
        #line default
        #line hidden
        
        
        #line 504 "..\..\..\Views\SettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal FFPOS.Controls.SettingToggleField TotalSummaBox;
        
        #line default
        #line hidden
        
        
        #line 505 "..\..\..\Views\SettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal FFPOS.Controls.SettingToggleField ColumnQtyStockBox;
        
        #line default
        #line hidden
        
        
        #line 506 "..\..\..\Views\SettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal FFPOS.Controls.SettingToggleField NewRowBox;
        
        #line default
        #line hidden
        
        
        #line 507 "..\..\..\Views\SettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal FFPOS.Controls.SettingToggleField EditPriceBox;
        
        #line default
        #line hidden
        
        
        #line 508 "..\..\..\Views\SettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal FFPOS.Controls.SettingToggleField DiscountBox;
        
        #line default
        #line hidden
        
        
        #line 510 "..\..\..\Views\SettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal FFPOS.Controls.SettingTripleChoiceField AppTypeBox;
        
        #line default
        #line hidden
        
        
        #line 537 "..\..\..\Views\SettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox PrinterNameDefaultBox;
        
        #line default
        #line hidden
        
        
        #line 543 "..\..\..\Views\SettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal FFPOS.Controls.SettingToggleField CheckPrintBox;
        
        #line default
        #line hidden
        
        
        #line 553 "..\..\..\Views\SettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock FiscalStatusText;
        
        #line default
        #line hidden
        
        
        #line 557 "..\..\..\Views\SettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal FFPOS.Controls.SettingToggleField FiscalModuleToggle;
        
        #line default
        #line hidden
        
        
        #line 562 "..\..\..\Views\SettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border FiscalDetailsPanel;
        
        #line default
        #line hidden
        
        
        #line 589 "..\..\..\Views\SettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal FFPOS.Controls.SettingToggleField MessagErrorBox;
        
        #line default
        #line hidden
        
        
        #line 590 "..\..\..\Views\SettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal FFPOS.Controls.SettingToggleField FiscalPrintCheckBox;
        
        #line default
        #line hidden
        
        
        #line 591 "..\..\..\Views\SettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal FFPOS.Controls.SettingTextField PrinterIpBox;
        
        #line default
        #line hidden
        
        
        #line 592 "..\..\..\Views\SettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal FFPOS.Controls.SettingTextField PageWidthBox;
        
        #line default
        #line hidden
        
        
        #line 593 "..\..\..\Views\SettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal FFPOS.Controls.SettingTextField TaxTypeBox;
        
        #line default
        #line hidden
        
        
        #line 594 "..\..\..\Views\SettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal FFPOS.Controls.SettingTextField VatCodeBox;
        
        #line default
        #line hidden
        
        
        #line 598 "..\..\..\Views\SettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal FFPOS.Controls.SettingTextField CommodityBox;
        
        #line default
        #line hidden
        
        
        #line 624 "..\..\..\Views\SettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal FFPOS.Controls.SettingRangeField SyncTimeInminBox;
        
        #line default
        #line hidden
        
        
        #line 625 "..\..\..\Views\SettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal FFPOS.Controls.SettingRangeField SyncDayBox;
        
        #line default
        #line hidden
        
        
        #line 626 "..\..\..\Views\SettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal FFPOS.Controls.SettingRangeField MaxDiscountBox;
        
        #line default
        #line hidden
        
        
        #line 627 "..\..\..\Views\SettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal FFPOS.Controls.SettingChoiceField FocusQtyBox;
        
        #line default
        #line hidden
        
        
        #line 629 "..\..\..\Views\SettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal FFPOS.Controls.SettingToggleField ReturnSaleBox;
        
        #line default
        #line hidden
        
        
        #line 630 "..\..\..\Views\SettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal FFPOS.Controls.SettingToggleField PeopleShowBox;
        
        #line default
        #line hidden
        
        
        #line 631 "..\..\..\Views\SettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal FFPOS.Controls.SettingToggleField PeoplePayBox;
        
        #line default
        #line hidden
        
        
        #line 632 "..\..\..\Views\SettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal FFPOS.Controls.SettingToggleField DebtSaleBox;
        
        #line default
        #line hidden
        
        
        #line 633 "..\..\..\Views\SettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal FFPOS.Controls.SettingToggleField DeleteRowBox;
        
        #line default
        #line hidden
        
        
        #line 650 "..\..\..\Views\SettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal FFPOS.Controls.SettingTextField AdminCodeBox;
        
        #line default
        #line hidden
        
        
        #line 658 "..\..\..\Views\SettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock ErrorText;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.10.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/TIJORAT_PRO_POS;component/views/settingswindow.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\Views\SettingsWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.10.0")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal System.Delegate _CreateDelegate(System.Type delegateType, string handler) {
            return System.Delegate.CreateDelegate(delegateType, this, handler);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.10.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            
            #line 17 "..\..\..\Views\SettingsWindow.xaml"
            ((FFPOS.Views.SettingsWindow)(target)).Loaded += new System.Windows.RoutedEventHandler(this.WindowLoaded);
            
            #line default
            #line hidden
            return;
            case 2:
            
            #line 284 "..\..\..\Views\SettingsWindow.xaml"
            ((System.Windows.Controls.Border)(target)).PreviewMouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.HeaderMouseLeftButtonDown);
            
            #line default
            #line hidden
            return;
            case 3:
            this.HeaderSubtitle = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 4:
            
            #line 304 "..\..\..\Views\SettingsWindow.xaml"
            ((System.Windows.Controls.TextBlock)(target)).PreviewMouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.HeaderMouseLeftButtonDown);
            
            #line default
            #line hidden
            return;
            case 5:
            this.BaseUrlBox = ((FFPOS.Controls.SettingTextField)(target));
            return;
            case 6:
            this.PublicUrlBox = ((FFPOS.Controls.SettingTextField)(target));
            return;
            case 7:
            this.StoreNameBox = ((FFPOS.Controls.SettingTextField)(target));
            return;
            case 8:
            this.StorePhoneBox = ((FFPOS.Controls.SettingTextField)(target));
            return;
            case 9:
            this.AppDateBox = ((FFPOS.Controls.SettingTextField)(target));
            return;
            case 10:
            this.AppStatusTextBox = ((FFPOS.Controls.SettingTextField)(target));
            return;
            case 11:
            
            #line 333 "..\..\..\Views\SettingsWindow.xaml"
            ((System.Windows.Controls.TextBlock)(target)).PreviewMouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.HeaderMouseLeftButtonDown);
            
            #line default
            #line hidden
            return;
            case 12:
            this.StoreSelectBox = ((System.Windows.Controls.ComboBox)(target));
            
            #line 341 "..\..\..\Views\SettingsWindow.xaml"
            this.StoreSelectBox.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.StoreSelectBox_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 13:
            this.StoreDetailsPanel = ((System.Windows.Controls.Border)(target));
            return;
            case 14:
            this.StoreNameInfoBox = ((FFPOS.Controls.SettingTextField)(target));
            return;
            case 15:
            this.StoreAgelNameBox = ((FFPOS.Controls.SettingTextField)(target));
            return;
            case 16:
            this.StoreLocationBox = ((FFPOS.Controls.SettingTextField)(target));
            return;
            case 17:
            this.StorePhoneInfoBox = ((FFPOS.Controls.SettingTextField)(target));
            return;
            case 18:
            this.StoreEmailBox = ((FFPOS.Controls.SettingTextField)(target));
            return;
            case 19:
            this.StoreSiteBox = ((FFPOS.Controls.SettingTextField)(target));
            return;
            case 20:
            this.StoreDescriptionBox = ((FFPOS.Controls.SettingTextField)(target));
            return;
            case 21:
            
            #line 396 "..\..\..\Views\SettingsWindow.xaml"
            ((System.Windows.Controls.TextBlock)(target)).PreviewMouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.HeaderMouseLeftButtonDown);
            
            #line default
            #line hidden
            return;
            case 22:
            this.DatabaseTypeBox = ((FFPOS.Controls.SettingChoiceField)(target));
            return;
            case 23:
            this.SqliteDetailsPanel = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 24:
            this.SQLitePathBox = ((FFPOS.Controls.SettingTextField)(target));
            return;
            case 25:
            this.MySqlDetailsPanel = ((System.Windows.Controls.Border)(target));
            return;
            case 26:
            this.MySqlHostBox = ((FFPOS.Controls.SettingTextField)(target));
            return;
            case 27:
            this.MySqlPortBox = ((FFPOS.Controls.SettingTextField)(target));
            return;
            case 28:
            this.MySqlDatabaseBox = ((FFPOS.Controls.SettingTextField)(target));
            return;
            case 29:
            this.MySqlUsernameBox = ((FFPOS.Controls.SettingTextField)(target));
            return;
            case 30:
            this.MySqlPasswordBox = ((FFPOS.Controls.SettingTextField)(target));
            return;
            case 31:
            this.TestMySqlButton = ((System.Windows.Controls.Button)(target));
            
            #line 457 "..\..\..\Views\SettingsWindow.xaml"
            this.TestMySqlButton.Click += new System.Windows.RoutedEventHandler(this.TestMySqlClicked);
            
            #line default
            #line hidden
            return;
            case 32:
            
            #line 501 "..\..\..\Views\SettingsWindow.xaml"
            ((System.Windows.Controls.TextBlock)(target)).PreviewMouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.HeaderMouseLeftButtonDown);
            
            #line default
            #line hidden
            return;
            case 33:
            this.IsTouchScreenBox = ((FFPOS.Controls.SettingToggleField)(target));
            return;
            case 34:
            this.TotalSummaBox = ((FFPOS.Controls.SettingToggleField)(target));
            return;
            case 35:
            this.ColumnQtyStockBox = ((FFPOS.Controls.SettingToggleField)(target));
            return;
            case 36:
            this.NewRowBox = ((FFPOS.Controls.SettingToggleField)(target));
            return;
            case 37:
            this.EditPriceBox = ((FFPOS.Controls.SettingToggleField)(target));
            return;
            case 38:
            this.DiscountBox = ((FFPOS.Controls.SettingToggleField)(target));
            return;
            case 39:
            this.AppTypeBox = ((FFPOS.Controls.SettingTripleChoiceField)(target));
            return;
            case 40:
            
            #line 522 "..\..\..\Views\SettingsWindow.xaml"
            ((System.Windows.Controls.TextBlock)(target)).PreviewMouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.HeaderMouseLeftButtonDown);
            
            #line default
            #line hidden
            return;
            case 41:
            this.PrinterNameDefaultBox = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 42:
            this.CheckPrintBox = ((FFPOS.Controls.SettingToggleField)(target));
            return;
            case 43:
            
            #line 551 "..\..\..\Views\SettingsWindow.xaml"
            ((System.Windows.Controls.TextBlock)(target)).PreviewMouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.HeaderMouseLeftButtonDown);
            
            #line default
            #line hidden
            return;
            case 44:
            this.FiscalStatusText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 45:
            this.FiscalModuleToggle = ((FFPOS.Controls.SettingToggleField)(target));
            return;
            case 46:
            this.FiscalDetailsPanel = ((System.Windows.Controls.Border)(target));
            return;
            case 47:
            this.MessagErrorBox = ((FFPOS.Controls.SettingToggleField)(target));
            return;
            case 48:
            this.FiscalPrintCheckBox = ((FFPOS.Controls.SettingToggleField)(target));
            return;
            case 49:
            this.PrinterIpBox = ((FFPOS.Controls.SettingTextField)(target));
            return;
            case 50:
            this.PageWidthBox = ((FFPOS.Controls.SettingTextField)(target));
            return;
            case 51:
            this.TaxTypeBox = ((FFPOS.Controls.SettingTextField)(target));
            return;
            case 52:
            this.VatCodeBox = ((FFPOS.Controls.SettingTextField)(target));
            return;
            case 53:
            this.CommodityBox = ((FFPOS.Controls.SettingTextField)(target));
            return;
            case 54:
            
            #line 607 "..\..\..\Views\SettingsWindow.xaml"
            ((System.Windows.Controls.TextBlock)(target)).PreviewMouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.HeaderMouseLeftButtonDown);
            
            #line default
            #line hidden
            return;
            case 55:
            this.SyncTimeInminBox = ((FFPOS.Controls.SettingRangeField)(target));
            return;
            case 56:
            this.SyncDayBox = ((FFPOS.Controls.SettingRangeField)(target));
            return;
            case 57:
            this.MaxDiscountBox = ((FFPOS.Controls.SettingRangeField)(target));
            return;
            case 58:
            this.FocusQtyBox = ((FFPOS.Controls.SettingChoiceField)(target));
            return;
            case 59:
            this.ReturnSaleBox = ((FFPOS.Controls.SettingToggleField)(target));
            return;
            case 60:
            this.PeopleShowBox = ((FFPOS.Controls.SettingToggleField)(target));
            return;
            case 61:
            this.PeoplePayBox = ((FFPOS.Controls.SettingToggleField)(target));
            return;
            case 62:
            this.DebtSaleBox = ((FFPOS.Controls.SettingToggleField)(target));
            return;
            case 63:
            this.DeleteRowBox = ((FFPOS.Controls.SettingToggleField)(target));
            return;
            case 64:
            this.AdminCodeBox = ((FFPOS.Controls.SettingTextField)(target));
            return;
            case 65:
            this.ErrorText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 66:
            
            #line 668 "..\..\..\Views\SettingsWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.ReloadClicked);
            
            #line default
            #line hidden
            return;
            case 67:
            
            #line 674 "..\..\..\Views\SettingsWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.SaveClicked);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

