#pragma checksum "..\..\..\Views\UserSettingsWindow.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "6C14FEBE387B4B62DAC6CDC055BB0D85C87779E3"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using FFPOS.Controls;
using MaterialDesignThemes.Wpf;
using MaterialDesignThemes.Wpf.Converters;
using MaterialDesignThemes.Wpf.Transitions;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace FFPOS.Views {
    
    
    /// <summary>
    /// UserSettingsWindow
    /// </summary>
    public partial class UserSettingsWindow : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 278 "..\..\..\Views\UserSettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock HeaderSubtitle;
        
        #line default
        #line hidden
        
        
        #line 305 "..\..\..\Views\UserSettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox StockBox;
        
        #line default
        #line hidden
        
        
        #line 320 "..\..\..\Views\UserSettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox CashBox;
        
        #line default
        #line hidden
        
        
        #line 333 "..\..\..\Views\UserSettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal FFPOS.Controls.SettingTextField UserNameBox;
        
        #line default
        #line hidden
        
        
        #line 338 "..\..\..\Views\UserSettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal FFPOS.Controls.SettingTextField UserLoginBox;
        
        #line default
        #line hidden
        
        
        #line 360 "..\..\..\Views\UserSettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox PrinterBox;
        
        #line default
        #line hidden
        
        
        #line 365 "..\..\..\Views\UserSettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal FFPOS.Controls.SettingToggleField CheckPrintBox;
        
        #line default
        #line hidden
        
        
        #line 374 "..\..\..\Views\UserSettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal FFPOS.Controls.SettingToggleField ShowProductImageBox;
        
        #line default
        #line hidden
        
        
        #line 375 "..\..\..\Views\UserSettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal FFPOS.Controls.SettingToggleField ShowSkuBox;
        
        #line default
        #line hidden
        
        
        #line 376 "..\..\..\Views\UserSettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal FFPOS.Controls.SettingToggleField ShowBarcodeBox;
        
        #line default
        #line hidden
        
        
        #line 377 "..\..\..\Views\UserSettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal FFPOS.Controls.SettingToggleField ShowStockQuantityBox;
        
        #line default
        #line hidden
        
        
        #line 378 "..\..\..\Views\UserSettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal FFPOS.Controls.SettingToggleField TableCompactModeBox;
        
        #line default
        #line hidden
        
        
        #line 398 "..\..\..\Views\UserSettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal FFPOS.Controls.SettingToggleField AutoSyncBox;
        
        #line default
        #line hidden
        
        
        #line 399 "..\..\..\Views\UserSettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal FFPOS.Controls.SettingToggleField SyncAfterSaleBox;
        
        #line default
        #line hidden
        
        
        #line 400 "..\..\..\Views\UserSettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal FFPOS.Controls.SettingRangeField SyncIntervalBox;
        
        #line default
        #line hidden
        
        
        #line 416 "..\..\..\Views\UserSettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal FFPOS.Controls.SettingToggleField ConfirmBeforeLogoutBox;
        
        #line default
        #line hidden
        
        
        #line 418 "..\..\..\Views\UserSettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal FFPOS.Controls.SettingTextField NoteBox;
        
        #line default
        #line hidden
        
        
        #line 431 "..\..\..\Views\UserSettingsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock ErrorText;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.10.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/TIJORAT_PRO_POS;component/views/usersettingswindow.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\Views\UserSettingsWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.10.0")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal System.Delegate _CreateDelegate(System.Type delegateType, string handler) {
            return System.Delegate.CreateDelegate(delegateType, this, handler);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.10.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            
            #line 17 "..\..\..\Views\UserSettingsWindow.xaml"
            ((FFPOS.Views.UserSettingsWindow)(target)).Loaded += new System.Windows.RoutedEventHandler(this.WindowLoaded);
            
            #line default
            #line hidden
            return;
            case 2:
            
            #line 270 "..\..\..\Views\UserSettingsWindow.xaml"
            ((System.Windows.Controls.Border)(target)).PreviewMouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.HeaderMouseLeftButtonDown);
            
            #line default
            #line hidden
            return;
            case 3:
            this.HeaderSubtitle = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 4:
            this.StockBox = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 5:
            this.CashBox = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 6:
            this.UserNameBox = ((FFPOS.Controls.SettingTextField)(target));
            return;
            case 7:
            this.UserLoginBox = ((FFPOS.Controls.SettingTextField)(target));
            return;
            case 8:
            this.PrinterBox = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 9:
            this.CheckPrintBox = ((FFPOS.Controls.SettingToggleField)(target));
            return;
            case 10:
            this.ShowProductImageBox = ((FFPOS.Controls.SettingToggleField)(target));
            return;
            case 11:
            this.ShowSkuBox = ((FFPOS.Controls.SettingToggleField)(target));
            return;
            case 12:
            this.ShowBarcodeBox = ((FFPOS.Controls.SettingToggleField)(target));
            return;
            case 13:
            this.ShowStockQuantityBox = ((FFPOS.Controls.SettingToggleField)(target));
            return;
            case 14:
            this.TableCompactModeBox = ((FFPOS.Controls.SettingToggleField)(target));
            return;
            case 15:
            this.AutoSyncBox = ((FFPOS.Controls.SettingToggleField)(target));
            return;
            case 16:
            this.SyncAfterSaleBox = ((FFPOS.Controls.SettingToggleField)(target));
            return;
            case 17:
            this.SyncIntervalBox = ((FFPOS.Controls.SettingRangeField)(target));
            return;
            case 18:
            this.ConfirmBeforeLogoutBox = ((FFPOS.Controls.SettingToggleField)(target));
            return;
            case 19:
            this.NoteBox = ((FFPOS.Controls.SettingTextField)(target));
            return;
            case 20:
            this.ErrorText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 21:
            
            #line 440 "..\..\..\Views\UserSettingsWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.CancelClicked);
            
            #line default
            #line hidden
            return;
            case 22:
            
            #line 446 "..\..\..\Views\UserSettingsWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.SaveClicked);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

