#pragma checksum "..\..\..\Controls\SettingTextField.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "B5444970D556D770F0A63FFFEE7043E8A177E451"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using MaterialDesignThemes.Wpf;
using MaterialDesignThemes.Wpf.Converters;
using MaterialDesignThemes.Wpf.Transitions;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace FFPOS.Controls {
    
    
    /// <summary>
    /// SettingTextField
    /// </summary>
    public partial class SettingTextField : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 5 "..\..\..\Controls\SettingTextField.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal FFPOS.Controls.SettingTextField Root;
        
        #line default
        #line hidden
        
        
        #line 36 "..\..\..\Controls\SettingTextField.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RowDefinition FieldRow;
        
        #line default
        #line hidden
        
        
        #line 39 "..\..\..\Controls\SettingTextField.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock HeaderText;
        
        #line default
        #line hidden
        
        
        #line 45 "..\..\..\Controls\SettingTextField.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border FieldBorder;
        
        #line default
        #line hidden
        
        
        #line 57 "..\..\..\Controls\SettingTextField.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal MaterialDesignThemes.Wpf.PackIcon IconHost;
        
        #line default
        #line hidden
        
        
        #line 65 "..\..\..\Controls\SettingTextField.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox InputBox;
        
        #line default
        #line hidden
        
        
        #line 72 "..\..\..\Controls\SettingTextField.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.PasswordBox PasswordInputBox;
        
        #line default
        #line hidden
        
        
        #line 81 "..\..\..\Controls\SettingTextField.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border FloatingHeaderText;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.10.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/TIJORAT_PRO_POS;component/controls/settingtextfield.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\Controls\SettingTextField.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.10.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.Root = ((FFPOS.Controls.SettingTextField)(target));
            return;
            case 2:
            this.FieldRow = ((System.Windows.Controls.RowDefinition)(target));
            return;
            case 3:
            this.HeaderText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 4:
            this.FieldBorder = ((System.Windows.Controls.Border)(target));
            return;
            case 5:
            this.IconHost = ((MaterialDesignThemes.Wpf.PackIcon)(target));
            return;
            case 6:
            this.InputBox = ((System.Windows.Controls.TextBox)(target));
            
            #line 69 "..\..\..\Controls\SettingTextField.xaml"
            this.InputBox.PreviewTextInput += new System.Windows.Input.TextCompositionEventHandler(this.InputBoxPreviewTextInput);
            
            #line default
            #line hidden
            return;
            case 7:
            this.PasswordInputBox = ((System.Windows.Controls.PasswordBox)(target));
            
            #line 75 "..\..\..\Controls\SettingTextField.xaml"
            this.PasswordInputBox.PasswordChanged += new System.Windows.RoutedEventHandler(this.PasswordInputBoxPasswordChanged);
            
            #line default
            #line hidden
            return;
            case 8:
            this.FloatingHeaderText = ((System.Windows.Controls.Border)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

