#pragma checksum "..\..\..\Controls\SettingRangeField.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "638EA25FF73FB0EA1BD257CE9996663441AE0DBA"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using MaterialDesignThemes.Wpf;
using MaterialDesignThemes.Wpf.Converters;
using MaterialDesignThemes.Wpf.Transitions;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace FFPOS.Controls {
    
    
    /// <summary>
    /// SettingRangeField
    /// </summary>
    public partial class SettingRangeField : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 5 "..\..\..\Controls\SettingRangeField.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal FFPOS.Controls.SettingRangeField Root;
        
        #line default
        #line hidden
        
        
        #line 27 "..\..\..\Controls\SettingRangeField.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock ValueText;
        
        #line default
        #line hidden
        
        
        #line 40 "..\..\..\Controls\SettingRangeField.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid TrackHost;
        
        #line default
        #line hidden
        
        
        #line 52 "..\..\..\Controls\SettingRangeField.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border FillBar;
        
        #line default
        #line hidden
        
        
        #line 59 "..\..\..\Controls\SettingRangeField.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border Thumb;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.10.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/TIJORAT_PRO_POS;component/controls/settingrangefield.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\Controls\SettingRangeField.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.10.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.Root = ((FFPOS.Controls.SettingRangeField)(target));
            return;
            case 2:
            this.ValueText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 3:
            this.TrackHost = ((System.Windows.Controls.Grid)(target));
            
            #line 43 "..\..\..\Controls\SettingRangeField.xaml"
            this.TrackHost.MouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.TrackMouseLeftButtonDown);
            
            #line default
            #line hidden
            
            #line 44 "..\..\..\Controls\SettingRangeField.xaml"
            this.TrackHost.MouseMove += new System.Windows.Input.MouseEventHandler(this.TrackMouseMove);
            
            #line default
            #line hidden
            
            #line 45 "..\..\..\Controls\SettingRangeField.xaml"
            this.TrackHost.MouseLeftButtonUp += new System.Windows.Input.MouseButtonEventHandler(this.TrackMouseLeftButtonUp);
            
            #line default
            #line hidden
            
            #line 46 "..\..\..\Controls\SettingRangeField.xaml"
            this.TrackHost.SizeChanged += new System.Windows.SizeChangedEventHandler(this.TrackHostSizeChanged);
            
            #line default
            #line hidden
            return;
            case 4:
            this.FillBar = ((System.Windows.Controls.Border)(target));
            return;
            case 5:
            this.Thumb = ((System.Windows.Controls.Border)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

