#pragma checksum "..\..\..\Controls\SettingTripleChoiceField.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "B2AE53386AD4AFAE3632CC3D517A946136EAC72C"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using MaterialDesignThemes.Wpf;
using MaterialDesignThemes.Wpf.Converters;
using MaterialDesignThemes.Wpf.Transitions;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace FFPOS.Controls {
    
    
    /// <summary>
    /// SettingTripleChoiceField
    /// </summary>
    public partial class SettingTripleChoiceField : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 5 "..\..\..\Controls\SettingTripleChoiceField.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal FFPOS.Controls.SettingTripleChoiceField Root;
        
        #line default
        #line hidden
        
        
        #line 60 "..\..\..\Controls\SettingTripleChoiceField.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button FirstButton;
        
        #line default
        #line hidden
        
        
        #line 62 "..\..\..\Controls\SettingTripleChoiceField.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal MaterialDesignThemes.Wpf.PackIcon FirstIcon;
        
        #line default
        #line hidden
        
        
        #line 63 "..\..\..\Controls\SettingTripleChoiceField.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock FirstLabel;
        
        #line default
        #line hidden
        
        
        #line 67 "..\..\..\Controls\SettingTripleChoiceField.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button SecondButton;
        
        #line default
        #line hidden
        
        
        #line 69 "..\..\..\Controls\SettingTripleChoiceField.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal MaterialDesignThemes.Wpf.PackIcon SecondIcon;
        
        #line default
        #line hidden
        
        
        #line 70 "..\..\..\Controls\SettingTripleChoiceField.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock SecondLabel;
        
        #line default
        #line hidden
        
        
        #line 74 "..\..\..\Controls\SettingTripleChoiceField.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ThirdButton;
        
        #line default
        #line hidden
        
        
        #line 76 "..\..\..\Controls\SettingTripleChoiceField.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal MaterialDesignThemes.Wpf.PackIcon ThirdIcon;
        
        #line default
        #line hidden
        
        
        #line 77 "..\..\..\Controls\SettingTripleChoiceField.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock ThirdLabel;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.10.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/TIJORAT_PRO_POS;component/controls/settingtriplechoicefield.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\Controls\SettingTripleChoiceField.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.10.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.Root = ((FFPOS.Controls.SettingTripleChoiceField)(target));
            return;
            case 2:
            this.FirstButton = ((System.Windows.Controls.Button)(target));
            
            #line 60 "..\..\..\Controls\SettingTripleChoiceField.xaml"
            this.FirstButton.Click += new System.Windows.RoutedEventHandler(this.FirstClicked);
            
            #line default
            #line hidden
            return;
            case 3:
            this.FirstIcon = ((MaterialDesignThemes.Wpf.PackIcon)(target));
            return;
            case 4:
            this.FirstLabel = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 5:
            this.SecondButton = ((System.Windows.Controls.Button)(target));
            
            #line 67 "..\..\..\Controls\SettingTripleChoiceField.xaml"
            this.SecondButton.Click += new System.Windows.RoutedEventHandler(this.SecondClicked);
            
            #line default
            #line hidden
            return;
            case 6:
            this.SecondIcon = ((MaterialDesignThemes.Wpf.PackIcon)(target));
            return;
            case 7:
            this.SecondLabel = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 8:
            this.ThirdButton = ((System.Windows.Controls.Button)(target));
            
            #line 74 "..\..\..\Controls\SettingTripleChoiceField.xaml"
            this.ThirdButton.Click += new System.Windows.RoutedEventHandler(this.ThirdClicked);
            
            #line default
            #line hidden
            return;
            case 9:
            this.ThirdIcon = ((MaterialDesignThemes.Wpf.PackIcon)(target));
            return;
            case 10:
            this.ThirdLabel = ((System.Windows.Controls.TextBlock)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

